import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header/header";
import Hero from "./components/hero/hero";
import Project from "./components/projects/projects";
import Footer from "./components/footer/footer";
import NetworkBackground from "./StarfieldBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-r from-black via-gray-800 to-gray-700 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NetworkBackground />
        <Navbar />
        <Hero />
        <Project />
        <Footer />
        {children}
      </body>
    </html>
  );
}
